spring:
  application:
    name: uber

  data:
    mongodb:
      uri: mongodb://localhost:27017/uberdatabase
      auto-index-creation: true

  datasource:
    url: jdbc:h2:mem:uberdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: mysupersecretkey123456789ubertoken
  expiration: 86400000  # 24 hours in ms

server:
  port: 8081

app:
  name: Uber App
  version: 1.0.0
  description: API for managing services replicating uber
  maintainer:
    name: Smit Rupani
    email: smitrupani@sst.com
