spring:
  application:
    name: uber

  data:
    mongodb:
      uri: mongodb://localhost:27017/uber

jwt:
  secret: mysupersecretkey123456789ubertoken
  expiration: 86400000  # 24 hours in ms

server:
  port: 8081

app:
  name: Uber App
  version: 1.0.0
  description: API for managing services replicating uber
  maintainer:
    name: Smit Rupani
    email: smitrupani@sst.com
